#!/usr/bin/env node
// scripts/publish-update.mjs
// ---------------------------------------------------------------------------
// Run after a successful desktop build to generate update-config.json.
//
// Usage:
//   node scripts/publish-update.mjs --base-url https://releases.example.com
//
// The script reads the sha512/size values from release/latest-mac.yml and
// release/latest.yml (already generated by electron-builder) and writes
// update-config.json with full download URLs. Commit update-config.json to
// the staging branch so Render picks it up on the next deploy.
//
// Options:
//   --base-url   HTTPS URL prefix where the release artefacts are hosted
//   --version    Override the version (default: read from release YML)
//   --critical   Mark the update as critical (default: false)
//   --notes      Comma-separated release notes (or set multiple --notes flags)
//   --min-ver    Minimum supported version (default: 1.0.200)
// ---------------------------------------------------------------------------

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT      = join(__dirname, '..')

// ── Arg parsing ─────────────────────────────────────────────────────────────

function arg(name, defaultVal = null) {
  const idx = process.argv.indexOf(`--${name}`)
  if (idx === -1) return defaultVal
  return process.argv[idx + 1] ?? defaultVal
}

function flag(name) { return process.argv.includes(`--${name}`) }

function allArgs(name) {
  const vals = []
  process.argv.forEach((v, i) => {
    if (v === `--${name}`) vals.push(process.argv[i + 1])
  })
  return vals
}

const baseUrl  = arg('base-url')
const critical = flag('critical')
const minVer   = arg('min-ver', '1.0.200')
const noteArgs = allArgs('notes').flatMap(n => n.split(',').map(s => s.trim()).filter(Boolean))

if (!baseUrl) {
  console.error('Error: --base-url is required')
  console.error('Example: node scripts/publish-update.mjs --base-url https://releases.example.com')
  process.exit(1)
}

const base = baseUrl.replace(/\/$/, '')

// ── Parse a YML manifest ────────────────────────────────────────────────────

function parseYml(text) {
  const lines = text.split('\n')
  const get   = (key) => {
    const line = lines.find(l => l.trimStart().startsWith(`${key}:`))
    return line ? line.split(':').slice(1).join(':').trim().replace(/^'|'$/g, '') : null
  }
  const files = []
  let inFiles = false
  let cur     = {}
  for (const raw of lines) {
    const line = raw.trimEnd()
    if (line === 'files:') { inFiles = true; continue }
    if (inFiles) {
      if (line.startsWith('  - url:')) { if (cur.url) files.push(cur); cur = { url: line.replace('  - url:', '').trim() }; continue }
      if (line.startsWith('    sha512:')) { cur.sha512 = line.replace('    sha512:', '').trim(); continue }
      if (line.startsWith('    size:'))   { cur.size   = parseInt(line.replace('    size:', '').trim(), 10); continue }
      if (!line.startsWith(' ') && !line.startsWith('\t')) { if (cur.url) files.push(cur); inFiles = false }
    }
  }
  if (cur.url) files.push(cur)
  return { version: get('version'), releaseDate: get('releaseDate'), files }
}

// ── Read generated manifests ─────────────────────────────────────────────────

const macYmlPath = join(ROOT, 'release', 'latest-mac.yml')
const winYmlPath = join(ROOT, 'release', 'latest.yml')

if (!existsSync(macYmlPath) || !existsSync(winYmlPath)) {
  console.error('Error: release/latest-mac.yml or release/latest.yml not found.')
  console.error('Run the desktop build first: npm run electron:build:mac && npm run electron:build:win')
  process.exit(1)
}

const mac = parseYml(readFileSync(macYmlPath, 'utf8'))
const win = parseYml(readFileSync(winYmlPath, 'utf8'))
const version     = arg('version') || mac.version
const releaseDate = mac.releaseDate || new Date().toISOString()

// The first file in latest-mac.yml is typically the .zip; the second is the .dmg
const macZip = mac.files.find(f => f.url.endsWith('.zip')) || mac.files[0]
const macDmg = mac.files.find(f => f.url.endsWith('.dmg'))

// Windows: Setup (universal), x64, arm64
const winAll    = win.files.find(f => f.url === 'BeeHive-Setup.exe')      || win.files[0]
const winX64    = win.files.find(f => f.url === 'BeeHive-Setup-x64.exe')
const winArm64  = win.files.find(f => f.url === 'BeeHive-Setup-arm64.exe')

const config = {
  version,
  releaseDate,
  critical,
  minimumVersion: minVer,
  notes: noteArgs.length > 0 ? noteArgs : ['Performance and reliability improvements'],
  mac: {
    url:      `${base}/${macZip.url}`,
    sha512:   macZip.sha512,
    size:     macZip.size,
    ...(macDmg ? {
      dmgUrl:    `${base}/${macDmg.url}`,
      dmgSha512: macDmg.sha512,
      dmgSize:   macDmg.size,
    } : {}),
  },
  win: {
    url:    `${base}/${winAll.url}`,
    sha512: winAll.sha512,
    size:   winAll.size,
    ...(winX64 ? {
      x64Url:    `${base}/${winX64.url}`,
      x64Sha512: winX64.sha512,
      x64Size:   winX64.size,
    } : {}),
    ...(winArm64 ? {
      arm64Url:    `${base}/${winArm64.url}`,
      arm64Sha512: winArm64.sha512,
      arm64Size:   winArm64.size,
    } : {}),
  },
}

const outPath = join(ROOT, 'update-config.json')
writeFileSync(outPath, JSON.stringify(config, null, 2) + '\n')
console.log(`✓ update-config.json written for v${version}`)
console.log(`  macOS  → ${config.mac.url}`)
console.log(`  Windows → ${config.win.url}`)
console.log(`  Critical: ${critical}`)
if (noteArgs.length) console.log(`  Notes:`, noteArgs)
console.log('\nNext steps:')
console.log('  1. Upload the release/ artefacts to', base)
console.log('  2. Commit update-config.json to staging')
console.log('  3. Push — Render redeploys and the update feed goes live')
